# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# This workflow will run evertime a new push is made to all branches, except for main

name: Staging

on:
  push:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Building
      run: npm run build --if-present
    - name: Check Linting
      run: npm run lint
    - name: Run Tests (Non E2E)
      run: npm test
      env:
        CI: true
